// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:67c22b9e-821f-4dcb-bc54-f1a815a68eaa',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '2308fb6ccfd047ae898257db54cbda34',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'eba3d227-0df0-4fec-a545-193f52f5b0b2',
    'aws_project_name': 'EzPz Local',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'ezpzlocal-mobilehub-1868190820',
}

export default awsmobile;
