// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:b7a7bc76-433e-4098-ab2c-3bd3f08217e7',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'ezpzorder-hosting-mobilehub-1495232504',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2205gb9f9t0n3.cloudfront.net',
    'aws_mobile_analytics_app_id': 'fda3aa92e7874635993ffa464f764f22',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7837d322-4eca-4f3e-9e06-970763cf3f92',
    'aws_project_name': 'ezpzorder',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'ezpzorder-mobilehub-1495232504',
}

export default awsmobile;
